//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeknoParrotUi.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TeknoParrotUi.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 由 Reaver、NTAuthority、avail 和社区提供 的本地化字符串。
        /// </summary>
        public static string AboutCredits {
            get {
                return ResourceManager.GetString("AboutCredits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加游戏 的本地化字符串。
        /// </summary>
        public static string AddGame {
            get {
                return ResourceManager.GetString("AddGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 返回 的本地化字符串。
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除游戏 的本地化字符串。
        /// </summary>
        public static string DeleteGame {
            get {
                return ResourceManager.GetString("DeleteGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载已取消 的本地化字符串。
        /// </summary>
        public static string DownloaderCancelled {
            get {
                return ResourceManager.GetString("DownloaderCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载完成 的本地化字符串。
        /// </summary>
        public static string DownloaderComplete {
            get {
                return ResourceManager.GetString("DownloaderComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载中 的本地化字符串。
        /// </summary>
        public static string DownloaderDownloading {
            get {
                return ResourceManager.GetString("DownloaderDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载错误 的本地化字符串。
        /// </summary>
        public static string DownloaderError {
            get {
                return ResourceManager.GetString("DownloaderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 允许的范围是 0-8191！ 的本地化字符串。
        /// </summary>
        public static string ErrorAllowedRange {
            get {
                return ResourceManager.GetString("ErrorAllowedRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TeknoParrotUI 似乎已经正在运行，要关闭它吗？ 的本地化字符串。
        /// </summary>
        public static string ErrorAlreadyRunning {
            get {
                return ResourceManager.GetString("ErrorAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法解析 GUID：{0}。请检查数据是否仅包含 GUID 值，不包含其他任何内容！ 的本地化字符串。
        /// </summary>
        public static string ErrorCannotParseGUID {
            get {
                return ResourceManager.GetString("ErrorCannotParseGUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载 ParrotData.xml 时发生异常！保存后会生成新的！
        ///
        ///{0} 的本地化字符串。
        /// </summary>
        public static string ErrorCantLoadParrotData {
            get {
                return ResourceManager.GetString("ErrorCantLoadParrotData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载 {0} 时出错，要删除它吗？ 的本地化字符串。
        /// </summary>
        public static string ErrorCantLoadProfile {
            get {
                return ResourceManager.GetString("ErrorCantLoadProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ParrotData.xml 保存期间发生异常！
        ///
        ///{0} 的本地化字符串。
        /// </summary>
        public static string ErrorCantSaveParrotData {
            get {
                return ResourceManager.GetString("ErrorCantSaveParrotData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未设置游戏位置！请在游戏设置中设置。 的本地化字符串。
        /// </summary>
        public static string ErrorGamePathNotSet {
            get {
                return ResourceManager.GetString("ErrorGamePathNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主服务器处于离线状态。 的本地化字符串。
        /// </summary>
        public static string ErrorMasterServerOffline {
            get {
                return ResourceManager.GetString("ErrorMasterServerOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 似乎您已将我提取到旧 TeknoParrot 的目录中。请将我提取到新目录中！ 的本地化字符串。
        /// </summary>
        public static string ErrorOldTeknoParrotDirectory {
            get {
                return ResourceManager.GetString("ErrorOldTeknoParrotDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 似乎这是您第一次运行 TeknoParrotUi，将进行模拟设置。 的本地化字符串。
        /// </summary>
        public static string FirstRun {
            get {
                return ResourceManager.GetString("FirstRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏： 的本地化字符串。
        /// </summary>
        public static string GameList {
            get {
                return ResourceManager.GetString("GameList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏运行中 的本地化字符串。
        /// </summary>
        public static string GameRunning {
            get {
                return ResourceManager.GetString("GameRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 由于您强制关闭了模拟器，您应该检查任务管理器中是否有任何与模拟器或游戏相关的仍在运行的进程。 的本地化字符串。
        /// </summary>
        public static string GameRunningCheckTaskMgr {
            get {
                return ResourceManager.GetString("GameRunningCheckTaskMgr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 强制退出游戏 的本地化字符串。
        /// </summary>
        public static string GameRunningForceQuit {
            get {
                return ResourceManager.GetString("GameRunningForceQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏停止 的本地化字符串。
        /// </summary>
        public static string GameRunningGameStopped {
            get {
                return ResourceManager.GetString("GameRunningGameStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏可执行文件： 的本地化字符串。
        /// </summary>
        public static string GameSettingsGameExecutable {
            get {
                return ResourceManager.GetString("GameSettingsGameExecutable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏可执行文件 的本地化字符串。
        /// </summary>
        public static string GameSettingsGameExecutableFilter {
            get {
                return ResourceManager.GetString("GameSettingsGameExecutableFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择游戏可执行文件 的本地化字符串。
        /// </summary>
        public static string GameSettingsSelectGameExecutable {
            get {
                return ResourceManager.GetString("GameSettingsSelectGameExecutable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 信息 的本地化字符串。
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该游戏是 64 位的，无法在 32 位操作系统上运行。 的本地化字符串。
        /// </summary>
        public static string Library64bit {
            get {
                return ResourceManager.GetString("Library64bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 似乎您已在使用其他模拟器。
        ///请从游戏目录中删除以下文件：
        ///   的本地化字符串。
        /// </summary>
        public static string LibraryAnotherEmulator {
            get {
                return ResourceManager.GetString("LibraryAnotherEmulator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请更新 OpenParrot！
        ///您似乎正在使用非官方的 {0} 文件！游戏可能会崩溃或不稳定。继续吗？ 的本地化字符串。
        /// </summary>
        public static string LibraryBadiDMAC {
            get {
                return ResourceManager.GetString("LibraryBadiDMAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法找到游戏 exe：{0} 的本地化字符串。
        /// </summary>
        public static string LibraryCantFindGame {
            get {
                return ResourceManager.GetString("LibraryCantFindGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 找不到 {0}！
        ///它可能已被您的杀毒软件删除。
        ///请重新解压 TeknoParrot。 的本地化字符串。
        /// </summary>
        public static string LibraryCantFindLoader {
            get {
                return ResourceManager.GetString("LibraryCantFindLoader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 控制器设置 的本地化字符串。
        /// </summary>
        public static string LibraryControllerSetup {
            get {
                return ResourceManager.GetString("LibraryControllerSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 这将下载 TeknoParrot 的所有缺失图标。文件大小约为 50 兆字节。您确定要继续吗？ 的本地化字符串。
        /// </summary>
        public static string LibraryDownloadAllIcons {
            get {
                return ResourceManager.GetString("LibraryDownloadAllIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载缺失的图标 的本地化字符串。
        /// </summary>
        public static string LibraryDownloadMissingIcons {
            get {
                return ResourceManager.GetString("LibraryDownloadMissingIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模拟器 的本地化字符串。
        /// </summary>
        public static string LibraryEmulator {
            get {
                return ResourceManager.GetString("LibraryEmulator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第二个游戏位置未设置！请在游戏设置中设置。 的本地化字符串。
        /// </summary>
        public static string LibraryGameLocation2NotSet {
            get {
                return ResourceManager.GetString("LibraryGameLocation2NotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未设置游戏位置！请在游戏设置中设置。 的本地化字符串。
        /// </summary>
        public static string LibraryGameLocationNotSet {
            get {
                return ResourceManager.GetString("LibraryGameLocationNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏设置 的本地化字符串。
        /// </summary>
        public static string LibraryGameSettings {
            get {
                return ResourceManager.GetString("LibraryGameSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您的游戏目录中可能存在一些无效文件。
        ///可能需要从游戏目录中删除以下文件，除非您知道它们是什么：
        ///   的本地化字符串。
        /// </summary>
        public static string LibraryInvalidFiles {
            get {
                return ResourceManager.GetString("LibraryInvalidFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单击“是”即可继续按原样运行游戏。 的本地化字符串。
        /// </summary>
        public static string LibraryInvalidFilesContinue {
            get {
                return ResourceManager.GetString("LibraryInvalidFilesContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动游戏 的本地化字符串。
        /// </summary>
        public static string LibraryLaunchGame {
            get {
                return ResourceManager.GetString("LibraryLaunchGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开Wiki 的本地化字符串。
        /// </summary>
        public static string LibraryMoreInfo {
            get {
                return ResourceManager.GetString("LibraryMoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 似乎您没有以管理员身份运行 TeknoParrotUI！游戏 {0} 要求 UI 以管理员身份运行才能正常运行。继续吗？ 的本地化字符串。
        /// </summary>
        public static string LibraryNeedsAdmin {
            get {
                return ResourceManager.GetString("LibraryNeedsAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您尚未设置游戏。要立即添加吗？ 的本地化字符串。
        /// </summary>
        public static string LibraryNoGames {
            get {
                return ResourceManager.GetString("LibraryNoGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 看来您正在尝试验证尚未有干净文件哈希列表的游戏。 的本地化字符串。
        /// </summary>
        public static string LibraryNoHashes {
            get {
                return ResourceManager.GetString("LibraryNoHashes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有可用的游戏信息 的本地化字符串。
        /// </summary>
        public static string LibraryNoInfo {
            get {
                return ResourceManager.GetString("LibraryNoInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测试菜单 的本地化字符串。
        /// </summary>
        public static string LibraryTestMenu {
            get {
                return ResourceManager.GetString("LibraryTestMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 切换测试模式 的本地化字符串。
        /// </summary>
        public static string LibraryToggleTestMode {
            get {
                return ResourceManager.GetString("LibraryToggleTestMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证游戏 的本地化字符串。
        /// </summary>
        public static string LibraryVerifyGame {
            get {
                return ResourceManager.GetString("LibraryVerifyGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关于 的本地化字符串。
        /// </summary>
        public static string MainAbout {
            get {
                return ResourceManager.GetString("MainAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你确定吗？ 的本地化字符串。
        /// </summary>
        public static string MainAreYouSure {
            get {
                return ResourceManager.GetString("MainAreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 库 的本地化字符串。
        /// </summary>
        public static string MainLibrary {
            get {
                return ResourceManager.GetString("MainLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出 的本地化字符串。
        /// </summary>
        public static string MainQuit {
            get {
                return ResourceManager.GetString("MainQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        public static string MainSettings {
            get {
                return ResourceManager.GetString("MainSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TeknoParrot 在线 的本地化字符串。
        /// </summary>
        public static string MainTPOnline {
            get {
                return ResourceManager.GetString("MainTPOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 否 的本地化字符串。
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成为赞助人！ 的本地化字符串。
        /// </summary>
        public static string PatreonBecomeAPatron {
            get {
                return ResourceManager.GetString("PatreonBecomeAPatron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消注册 Patreon 密钥 的本地化字符串。
        /// </summary>
        public static string PatreonDeregisterKey {
            get {
                return ResourceManager.GetString("PatreonDeregisterKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 来自其他进程的错误： 的本地化字符串。
        /// </summary>
        public static string PatreonError {
            get {
                return ResourceManager.GetString("PatreonError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Patreon Key 不能为空 的本地化字符串。
        /// </summary>
        public static string PatreonMustNotBeBlank {
            get {
                return ResourceManager.GetString("PatreonMustNotBeBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注册 Patreon 密钥 的本地化字符串。
        /// </summary>
        public static string PatreonRegisterKey {
            get {
                return ResourceManager.GetString("PatreonRegisterKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态： 的本地化字符串。
        /// </summary>
        public static string PatreonStatus {
            get {
                return ResourceManager.GetString("PatreonStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动时检查更新 的本地化字符串。
        /// </summary>
        public static string SettingsCheckForUpdates {
            get {
                return ResourceManager.GetString("SettingsCheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出时确认提示 的本地化字符串。
        /// </summary>
        public static string SettingsConfirmExit {
            get {
                return ResourceManager.GetString("SettingsConfirmExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Direct Input 转向设置 的本地化字符串。
        /// </summary>
        public static string SettingsDInputWheel {
            get {
                return ResourceManager.GetString("SettingsDInputWheel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载力反馈插件 的本地化字符串。
        /// </summary>
        public static string SettingsDownloadFFB {
            get {
                return ResourceManager.GetString("SettingsDownloadFFB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择后下载游戏图标 的本地化字符串。
        /// </summary>
        public static string SettingsDownloadIcon {
            get {
                return ResourceManager.GetString("SettingsDownloadIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全线性刹车 的本地化字符串。
        /// </summary>
        public static string SettingsFullBrake {
            get {
                return ResourceManager.GetString("SettingsFullBrake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全线性油门 的本地化字符串。
        /// </summary>
        public static string SettingsFullGas {
            get {
                return ResourceManager.GetString("SettingsFullGas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在 UI 中禁用硬件加速 的本地化字符串。
        /// </summary>
        public static string SettingsHardwareAccel {
            get {
                return ResourceManager.GetString("SettingsHardwareAccel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 隐藏控制台窗口 的本地化字符串。
        /// </summary>
        public static string SettingsHideConsoleWindows {
            get {
                return ResourceManager.GetString("SettingsHideConsoleWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操纵杆设置 的本地化字符串。
        /// </summary>
        public static string SettingsJoystickGunSettings {
            get {
                return ResourceManager.GetString("SettingsJoystickGunSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载启动时玩的最后一款游戏 的本地化字符串。
        /// </summary>
        public static string SettingsLoadLastPlayed {
            get {
                return ResourceManager.GetString("SettingsLoadLastPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 玩家 1 操纵杆灵敏度 的本地化字符串。
        /// </summary>
        public static string SettingsP1GunJoystickSensitivity {
            get {
                return ResourceManager.GetString("SettingsP1GunJoystickSensitivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 玩家 2 操纵杆灵敏度 的本地化字符串。
        /// </summary>
        public static string SettingsP2GunJoystickSensitivity {
            get {
                return ResourceManager.GetString("SettingsP2GunJoystickSensitivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 反向线性刹车 的本地化字符串。
        /// </summary>
        public static string SettingsReverseBrake {
            get {
                return ResourceManager.GetString("SettingsReverseBrake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 反向线性油门 的本地化字符串。
        /// </summary>
        public static string SettingsReverseGas {
            get {
                return ResourceManager.GetString("SettingsReverseGas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存设置 的本地化字符串。
        /// </summary>
        public static string SettingsSaveSettings {
            get {
                return ResourceManager.GetString("SettingsSaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在 Discord 上显示正在玩的游戏 的本地化字符串。
        /// </summary>
        public static string SettingsShowGameOnDiscord {
            get {
                return ResourceManager.GetString("SettingsShowGameOnDiscord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用 sTo0z 区域 的本地化字符串。
        /// </summary>
        public static string SettingsSto0zZone {
            get {
                return ResourceManager.GetString("SettingsSto0zZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标题颜色 的本地化字符串。
        /// </summary>
        public static string SettingsUIColour {
            get {
                return ResourceManager.GetString("SettingsUIColour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UI 定制 (Patreon) 的本地化字符串。
        /// </summary>
        public static string SettingsUICustomization {
            get {
                return ResourceManager.GetString("SettingsUICustomization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 深色模式 的本地化字符串。
        /// </summary>
        public static string SettingsUIDarkMode {
            get {
                return ResourceManager.GetString("SettingsUIDarkMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在节假日使用不同的主题 的本地化字符串。
        /// </summary>
        public static string SettingsUIHolidayThemes {
            get {
                return ResourceManager.GetString("SettingsUIHolidayThemes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已成功保存 {0}！ 的本地化字符串。
        /// </summary>
        public static string SuccessfullySaved {
            get {
                return ResourceManager.GetString("SuccessfullySaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建大厅并启动游戏 的本地化字符串。
        /// </summary>
        public static string TPOCreateLobby {
            get {
                return ResourceManager.GetString("TPOCreateLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按游戏筛选： 的本地化字符串。
        /// </summary>
        public static string TPOFilter {
            get {
                return ResourceManager.GetString("TPOFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏 的本地化字符串。
        /// </summary>
        public static string TPOGame {
            get {
                return ResourceManager.GetString("TPOGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加入大厅并启动游戏 的本地化字符串。
        /// </summary>
        public static string TPOJoinLobby {
            get {
                return ResourceManager.GetString("TPOJoinLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大厅名称 的本地化字符串。
        /// </summary>
        public static string TPOLobbyName {
            get {
                return ResourceManager.GetString("TPOLobbyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 玩家 的本地化字符串。
        /// </summary>
        public static string TPOPlayers {
            get {
                return ResourceManager.GetString("TPOPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷新大厅 的本地化字符串。
        /// </summary>
        public static string TPORefresh {
            get {
                return ResourceManager.GetString("TPORefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有新的更新可用。 的本地化字符串。
        /// </summary>
        public static string UpdaterAvailable {
            get {
                return ResourceManager.GetString("UpdaterAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未安装 的本地化字符串。
        /// </summary>
        public static string UpdaterNotInstalled {
            get {
                return ResourceManager.GetString("UpdaterNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开变更日志 的本地化字符串。
        /// </summary>
        public static string UpdaterOpenChangelog {
            get {
                return ResourceManager.GetString("UpdaterOpenChangelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您希望 TeknoParrotUi 重新启动以完成更新吗？否则，TeknoParrotUi 将关闭。 的本地化字符串。
        /// </summary>
        public static string UpdaterRestart {
            get {
                return ResourceManager.GetString("UpdaterRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已成功将 {0} 更新为 {1} 的本地化字符串。
        /// </summary>
        public static string UpdaterSuccess {
            get {
                return ResourceManager.GetString("UpdaterSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新 的本地化字符串。
        /// </summary>
        public static string UpdaterUpdate {
            get {
                return ResourceManager.GetString("UpdaterUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TeknoParrot 检测到您目前正在运行 VALORANT 的反作弊系统 Riot Vanguard。Vanguard 会干扰 TeknoParrot 加载游戏的方式，并且已知会导致问题！
        ///
        ///强烈建议您右键单击系统托盘中的 Vanguard 图标（时钟旁边），然后单击“退出 Vanguard”。这意味着您无法玩 VALORANT，直到您重新启动计算机，但 TeknoParrot 游戏现在应该可以正常启动。
        ///
        ///单击“确定”继续加载 TeknoParrot。 的本地化字符串。
        /// </summary>
        public static string VanguardDetected {
            get {
                return ResourceManager.GetString("VanguardDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证已取消。 的本地化字符串。
        /// </summary>
        public static string VerifyCancelled {
            get {
                return ResourceManager.GetString("VerifyCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在验证游戏完整性... 的本地化字符串。
        /// </summary>
        public static string VerifyChecking {
            get {
                return ResourceManager.GetString("VerifyChecking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏文件无效 的本地化字符串。
        /// </summary>
        public static string VerifyFilesInvalid {
            get {
                return ResourceManager.GetString("VerifyFilesInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您的游戏似乎包含无效文件。这可能是由于下载错误、转储错误、病毒感染，或者您安装了分辨率和英文补丁等修改程序。 的本地化字符串。
        /// </summary>
        public static string VerifyFilesInvalidExplain {
            get {
                return ResourceManager.GetString("VerifyFilesInvalidExplain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏文件有效 的本地化字符串。
        /// </summary>
        public static string VerifyFilesValid {
            get {
                return ResourceManager.GetString("VerifyFilesValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效的： 的本地化字符串。
        /// </summary>
        public static string VerifyInvalid {
            get {
                return ResourceManager.GetString("VerifyInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有效的： 的本地化字符串。
        /// </summary>
        public static string VerifyValid {
            get {
                return ResourceManager.GetString("VerifyValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 警告 的本地化字符串。
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是 的本地化字符串。
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
